version: "3.5"
volumes:
  redis_volume:
services:
  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis_volume:/data